\u srgp

DROP TABLE IF EXISTS dim_polling_district
;

CREATE TABLE dim_polling_district
(   dpd_id             int(4) NOT NULL AUTO_INCREMENT
  , dpd_dw_id          tinyint
  , dpd_name           VARCHAR(100)
  , dpd_short_name     CHAR(2)
  , dpd_2013_count     int(6)
  , PRIMARY KEY (dpd_id)
  , CONSTRAINT fk1_dpd_dw_id FOREIGN KEY fk1_dpd_dw_id (dpd_dw_id) REFERENCES dim_ward (dw_id)
     )   
     ENGINE=InnoDB
     CHARACTER SET=utf8
     COLLATE=utf8_unicode_ci
     COMMENT="Holds Polling District Dimension"
;

INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (1,"Arbourthorne East","AA",2532);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (1,"Arbourthorne West","AB",1548);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (1,"Gleadless Common","AC",2544);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (1,"Hurlfield","AD",2193);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (1,"Myrtle Road","AE",2775);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (1,"Norfolk Park","AF",1916);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (2,"Batemoor","BA",3024);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (2,"Chancet Wood","BB",826);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (2,"Dalewood","BC",1362);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (2,"Greenhill","BD",2126);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (2,"Hemper Lane","BE",2399);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (2,"Low Edges East","BF",1516);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (2,"Low Edges West","BG",2614);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (3,"Hackenthorpe","CA",2451);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (3,"Manvers","CB",1710);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (3,"Owlthorpe","CC",2664);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (3,"Sothall","CD",2406);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (3,"Sothall South","CE",2103);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (3,"Victoria","CF",2051);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (4,"Base Green","DA",2153);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (4,"Birley Moor","DB",1297);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (4,"Birley Spa","DC",3408);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (4,"Charnock Hall","DD",2835);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (4,"Frecheville","DE",2266);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (4,"Silkstone","DF",1071);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (5,"Botanical","EA",2524);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (5,"Brocco Bank","EB",820);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (5,"Collegiate","EC",1235);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (5,"Commonside","ED",1594);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (5,"Harcourt","EE",1594);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (5,"Summerfield","EF",1650);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (5,"Tapton Hill","EG",1480);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (5,"Whitham","EH",2414);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Abbeyfield","FA",1828);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Busk Meadow","FB",1201);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Carwood","FC",951);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Fir Vale","FD",2940);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Firshill","FE",1552);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Hinde House","FF",1540);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Lightways","FG",1066);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Parkwood","FH",959);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Pyebank","FI",1170);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Shirecliffe","FJ",1392);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (6,"Spital Hill","FK",1456);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Arundel","GA",1256);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Broomhall","GB",2112);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Catherdral","GC",2558);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Cemetery Road","GD",2282);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Edmund","GE",2260);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Highfield","GF",3224);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Kelham","GG",2067);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Springfield","GH",2932);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (7,"Wostenholm","GI",2164);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (8,"Cobden","HA",2759);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (8,"Crosspool","HB",2779);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (8,"St. Thomas'","HC",2609);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (8,"St. Timothy's","HD",1674);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (8,"Sandygate","HE",1071);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (8,"Sandygate Park","HF",1350);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (8,"Toftwood","HG",1857);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (9,"Acres Hill","IA",2507);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (9,"Attercliffe","IB",3078);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (9,"Bowden Housteds","IC",2080);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (9,"Carbrook","ID",2797);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (9,"Fitzalan","IE",2373);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (9,"Greenland","IF",1281);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (9,"High Hazels","IG",1884);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (10,"Abbeydale Park","JA",3080);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (10,"Bradway","JB",3097);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (10,"Dore","JC",3088);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (10,"Totley","JD",3087);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (10,"Whirlow","JE",1263);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (11,"Blackburn","KA",1494);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (11,"Chapeltown","KB",3092);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (11,"Ecclesfield","KC",2761);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (11,"Ecclesfield Common","KD",1102);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (11,"High Greave","KE",1272);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (11,"Horbury","KF",2175);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (11,"Warren","KG",894);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (11,"Wheata","KH",1783);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (12,"All Saints","LA",2306);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (12,"Banner Cross","LB",1149);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (12,"Bents Green","LC",2837);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (12,"Greystones","LD",3114);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (12,"Millhouses","LE",2989);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (12,"Mylnhurst","LF",2599);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (13,"Beavercotes","MA",2428);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (13,"Elm Lane","MB",1525);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (13,"Horninglow","MC",1602);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (13,"Lindsay","MD",3033);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (13,"Longley","ME",2521);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (13,"Longley Hall","MF",899);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (13,"Moonshine","MG",845);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (13,"Shiregreen","MH",1645);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (14,"Canterbury","NA",2933);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (14,"Endcliffe Edge","NB",1912);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (14,"Endcliffe Ridge","NC",2078);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (14,"Hallamshire","ND",2332);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (14,"Lodge Moor","NE",1545);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (14,"Nether Green","NF",2111);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (14,"Ranmoor","NG",1454);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (15,"Abney","OA",919);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (15,"Heeley","OB",2982);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (15,"Hemsworth","OC",1462);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (15,"Herdings","OD",1241);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (15,"Mawfa","OE",2021);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (15,"Meersbrook","OF",1949);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (15,"Meersbrook Park","OG",2185);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (15,"Newfield Green","OH",1908);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (16,"Archer","PA",1929);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (16,"Little Norton","PB",1508);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (16,"Meadhowhead","PC",2881);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (16,"Norton","PD",1121);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (16,"Norton Lees","PE",1802);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (16,"Norton Woodseats","PF",2171);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (16,"Woodseats","PG",2222);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (17,"Dorothy","QA",1497);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (17,"Dykes Hall","QB",1869);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (17,"Malin Bridge","QC",2195);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (17,"Marlcliffe","QD",2798);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (17,"Parkwood","QE",2611);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (17,"Wadsley Park","QF",905);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (17,"Wisewood","QG",2228);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (18,"Fairleigh","RA",2415);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (18,"Lower Manor","RB",2039);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (18,"Manor Park","RC",1687);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (18,"Park Hill","RD",1905);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (18,"Skye Edge","RE",1669);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (18,"Stafford","RF",2187);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (18,"Wybourn","RG",1957);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (19,"Halfway","SA",2551);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (19,"Mosborough","SB",1806);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (19,"Mosborough Moor","SC",2181);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (19,"Waterthorpe","SD",3203);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (19,"Westfield","SE",2565);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (19,"Windmill","SF",1516);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (20,"Carterknowle","TA",2991);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (20,"Clifford","TB",2925);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (20,"Edgebrook","TC",3020);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (20,"Hunter's Bar","TD",1831);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (20,"Kenwood","TE",2878);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (21,"Elm Tree","UA",2123);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (21,"Intake","UB",2369);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (21,"Linley Lane","UC",1230);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (21,"Seagrave","UD",1406);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (21,"Spinkhill","UE",2182);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (21,"Stradbroke","UF",2639);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (21,"Woodthorpe","UG",1506);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (22,"Beck Road","VA",2875);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (22,"Concord","VB",1583);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (22,"Hartley Brook","VC",3439);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (22,"Jenkin","VD",2338);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (22,"Lower Wincobank","VE",2209);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (22,"Upwell","VF",982);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (22,"Wincobank","VG",1295);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (23,"Binsted","WA",1865);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (23,"Birley Carr","WB",2001);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (23,"Chaucer","WC",2112);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (23,"Fox Hill","WD",2178);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (23,"Mansel","WE",1427);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (23,"Parson Cross","WF",2746);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (23,"Southey Green","WG",1553);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Bradfield","XA",331);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Dunworth","XB",328);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Liberty Hill","XC",1130);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Loxley","XD",1595);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Marchwood","XE",2347);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Stannington North","XF",3115);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Stannington South","XG",1138);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Stanwood","XH",1545);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Wadsley Park","XI",1933);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (24,"Worrall","XJ",1024);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Bolsterstone","YA",342);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Deepcar","YB",1923);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Garden Village","YC",1324);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Midhopestones","YD",102);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Oughtibridge East","YE",1216);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Oughtibridge West","YF",1711);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"St. John's","YG",1183);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Shay House","YH",1057);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Smithy Moor","YI",974);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Stubbin","YJ",2338);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Town","YK",1375);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (25,"Wharncliffe Side","YL",1166);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Bole Hill","ZA",723);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Burgoyne","ZB",1260);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Howard Road","ZC",1353);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Langsett","ZD",1184);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Lower Walkley","ZE",2319);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Netherthorpe","ZF",2200);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Philadelphia","ZG",619);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"South Road","ZH",1650);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Upperthorpe","ZI",1800);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (26,"Walkley Bank","ZJ",1818);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (27,"Angram Bank","2A",2420);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (27,"Burncross","2B",3267);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (27,"Grenoside No. 1","2C",1640);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (27,"Grenoside No. 2","2D",1829);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (27,"Mortomley","2E",3274);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (27,"Wortley Road","2F",1946);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (28,"Handsworth","3A",3172);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (28,"Handsworth Grange","3B",2100);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (28,"Woodhouse Central","3C",2832);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (28,"Woodhouse East","3D",2209);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (28,"Woodhouse Mill","3E",1272);
INSERT INTO dim_polling_district (dpd_dw_id, dpd_name, dpd_short_name, dpd_2013_count) VALUES (28,"Woodhouse West","3F",1987);


\q
